----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhCN" then
    return
end

BTWQUESTS_AID_OF_THE_ILLIDARI = "伊利达雷的援手"
BTWQUESTS_ARTIFACT = "神器"
BTWQUESTS_FATE_OF_THE_TIDESKORN = "蔑潮的命运"
BTWQUESTS_RUMBLINGS_NEAR_FELTOTEM = "邪能图腾的骚动"
BTWQUESTS_THE_BRADENSBROOK_INVESTIGATION = "鲑鱼溪调查"
BTWQUESTS_THE_FOLLY_OF_LEVIA_LAURENCE = "莱维娅·劳伦斯的窘境"
BTWQUESTS_THE_THIEVING_APPRENTICE = "顺手牵羊"
BTWQUESTS_THE_TWISTED_TWINS = "扭曲的双子"
