_G['BTWQUESTS_EXPANSION_NAME' .. BTWQUESTS_EXPANSION_CLASSIC] = EXPANSION_NAME0 or "Classic";
_G['BTWQUESTS_EXPANSION_NAME' .. BTWQUESTS_EXPANSION_BURNING_CRUSADE] = EXPANSION_NAME1 or "The Burning Crusade";
_G['BTWQUESTS_EXPANSION_NAME' .. BTWQUESTS_EXPANSION_WRATH_OF_THE_LICH_KING] = EXPANSION_NAME2 or "Wrath of the Lich King";
_G['BTWQUESTS_EXPANSION_NAME' .. BTWQUESTS_EXPANSION_CATACLYSM] = EXPANSION_NAME3 or "Cataclysm";
_G['BTWQUESTS_EXPANSION_NAME' .. BTWQUESTS_EXPANSION_MISTS_OF_PANDARIA] = EXPANSION_NAME4 or "Mists of Pandaria";
_G['BTWQUESTS_EXPANSION_NAME' .. BTWQUESTS_EXPANSION_WARLORDS_OF_DRAENOR] = EXPANSION_NAME5 or "Warlords of Draenor";
_G['BTWQUESTS_EXPANSION_NAME' .. BTWQUESTS_EXPANSION_LEGION] = EXPANSION_NAME6 or "Legion";
_G['BTWQUESTS_EXPANSION_NAME' .. BTWQUESTS_EXPANSION_BFA] = EXPANSION_NAME7 or "Battle for Azeroth";

BTWQUESTS_QUEST_JOURNAL = "Quest Journal"
BTWQUESTS_ARTIFACT = "Artifact"
BTWQUESTS_ORDERHALL = "Order Hall"
BTWQUESTS_LEVEL = "Level %d"
BTWQUESTS_INTRODUCTION = "Introduction"
BTWQUESTS_QUEST_CHAIN_COMPLETED = GREEN_FONT_COLOR_CODE.."You have completed this quest chain"..FONT_COLOR_CODE_CLOSE
BTWQUESTS_QUEST_CHAIN_ACTIVE = GREEN_FONT_COLOR_CODE.."You are on this quest chain"..FONT_COLOR_CODE_CLOSE
BTWQUESTS_REQUIREMENT_PROGRESS = "Requirement progress"
BTWQUESTS_REQUIREMENTS = "%d/%d Requirements"
BTWQUESTS_REPUTATION_AMOUNT_STANDING = "%s into %s with %s"
BTWQUESTS_REPUTATION_STANDING = "%s with %s"

BTWQUESTS_RETURN_TO_ORDER_HALL = "Return to your Order Hall"
BTWQUESTS_GO_TO_THE_FELBLOOD_ALTER = "Go to the Felblood Alter"
BTWQUESTS_KILL_NIGHTBORNE = "Kill Nightborne"
BTWQUESTS_GO_TO_LYREA_WINDFEATHER = "Go to Lyrea Windfeather"
BTWQUESTS_GO_TO_IVANEL_MEADOWSONG = "Go to Ivanel Meadowsong"
BTWQUESTS_GO_TO_THAEDRIS_FEATHERSONG = "Go to Thaedris Feathersong"
BTWQUESTS_THAEDRIS_FEATHERSONG = "Thaedris Feathersong"
BTWQUESTS_KILL_THE_STARVING_ETTIN = "Kill the Starving Ettin"
BTWQUESTS_RETURN_TO_IRONGROVE_RETRAT = "Return to Irongrove Retreat"
BTWQUESTS_GO_TO_NIGHTEYES = "Go to Nighteyes"
BTWQUESTS_NIGHTEYES = "Nighteyes"

BTWQUESTS_COMPLETE_ORDER_HALL_CAMPAIGN = "Complete your Order Campaign"
BTWQUESTS_THE_THIEVING_APPRENTICE = "The Thieving Apprentice"
BTWQUESTS_FATE_OF_THE_TIDESKORN = "Fate of the Tideskorn"
BTWQUESTS_AID_OF_THE_ILLIDARI = "Aid of the Illidari"
BTWQUESTS_THE_BRADENSBROOK_INVESTIGATION = "The Bradensbrook Investigation"
BTWQUESTS_RUMBLINGS_NEAR_FELTOTEM = "Rumblings Near Feltotem"
BTWQUESTS_THE_FOLLY_OF_LEVIA_LAURENCE = "The Folly of Levia Laurence"
BTWQUESTS_THE_TWISTED_TWINS = "The Twisted Twin"

BTWQUESTS_LIGHTS_HEART = "Light's Heart"

BTWQUESTS_KILL_CHAMPIONS = "Kill Champions"
BTWQUESTS_KILL_DRAGONS = "Kill Dragons"

BTWQUESTS_DEATHKNIGHT_CAMPAIGN = "Deathlord Campaign"
BTWQUESTS_DEATHKNIGHT_MOUNT = "Mount: Deathlord's Vilebrood Vanquisher"

BTWQUESTS_DEMONHUNTER_CAMPAIGN = "Slayer Campaign"
BTWQUESTS_DEMONHUNTER_MOUNT = "Mount: Slayer's Felbroken Shrieker"

BTWQUESTS_DRUID_CAMPAIGN = "Archdruid Campaign"
BTWQUESTS_DRUID_MOUNT = "Mount: Archdruid's Lunarwing Form"

BTWQUESTS_HUNTER_CAMPAIGN = "Huntmaster Campaign"
BTWQUESTS_HUNTER_MOUNT = "Mount: Huntmaster's Loyal Wolfhawk"

BTWQUESTS_MAGE_CAMPAIGN = "Archmage Campaign"
BTWQUESTS_MAGE_MOUNT = "Mount: Archmage's Prismatic Disc"

BTWQUESTS_MONK_CAMPAIGN = "Brewmaster Campaign"
BTWQUESTS_MONK_MOUNT = "Mount: Ban-Lu, Grandmaster's Companion"

BTWQUESTS_PALADIN_CAMPAIGN = "Highlord Campaign"
BTWQUESTS_PALADIN_MOUNT = "Mount: Highlord's Golden Charger"

BTWQUESTS_PRIEST_CAMPAIGN = "High Priest Campaign"
BTWQUESTS_PRIEST_MOUNT = "Mount: High Priest's Lightsworn Seeker"

BTWQUESTS_ROGUE_CAMPAIGN = "Shadowblade Campaign"
BTWQUESTS_ROGUE_MOUNT = "Mount: Shadowblade's Murderous Omen"

BTWQUESTS_SHAMAN_CAMPAIGN = "Farseer Campaign"
BTWQUESTS_SHAMAN_MOUNT = "Mount: Farseer's Raging Tempest"

BTWQUESTS_WARLOCK_CAMPAIGN = "Netherlord Campaign"
BTWQUESTS_WARLOCK_MOUNT = "Mount: Netherlord's Chaotic Wrathsteed"

BTWQUESTS_WARRIOR_CAMPAIGN = "Battelord Campaign"
BTWQUESTS_WARRIOR_MOUNT = "Mount: Battlelord's Bloodthirsty War Wyrm"

BTWQUESTS_SECRET = "Secret"
BTWQUESTS_RARE_KOSUMOTH = "Rare: Kosumoth the Hungering"
BTWQUESTS_MOUNT_RIDDLERS = "Mount: Riddler's Mind-Worm"
BTWQUESTS_PET_SUNDARTER = "Pet: Sun Darter Hatchling"
BTWQUESTS_MOUNT_LUCID_NIGHTMARE = "Mount: Lucid Nightmare"

BTWQUESTS_EPILOGUE = "Epilogue"
BTWQUESTS_PROFESSIONS = "Professions"
BTWQUESTS_PROFESSION_ALCHEMY = "Alchemy"
BTWQUESTS_PROFESSION_BLACKSMITHING = "Blacksmithing"
BTWQUESTS_PROFESSION_ENCHANTING = "Enchanting"
BTWQUESTS_PROFESSION_ENGINEERING = "Engineering"
BTWQUESTS_PROFESSION_FIRST_AID = "First Aid"
BTWQUESTS_PROFESSION_HERBALISM = "Herbalism"
BTWQUESTS_PROFESSION_INSCRIPTION = "Inscription"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "Jewelcrafting"
BTWQUESTS_PROFESSION_LEATHERWORKING = "Leatherworking"
BTWQUESTS_PROFESSION_MINING = "Mining"
BTWQUESTS_PROFESSION_SKINNING = "Skinning"
BTWQUESTS_PROFESSION_TAILORING = "Tailoring"
BTWQUESTS_PROFESSION_FISHING = "Fishing"
BTWQUESTS_WAIT_NAT_PAGLE = "Wait for Nat Pagle (May require relogging)"
BTWQUESTS_THE_UNDERLIGHT_ANGLER = "The Underlight Angler"
BTWQUESTS_FISH_LUMINOUS_PEARL = "Fish up the Luminous Pearl from pools"
BTWQUESTS_TOOLTIP_PREREQUISITES = "Prerequisites:"