----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhTW" then
    return
end

BTWQUESTS_AID_OF_THE_ILLIDARI = "伊利達瑞的援助"
BTWQUESTS_ARTIFACT = "神器"
BTWQUESTS_FATE_OF_THE_TIDESKORN = "蔑潮的命運"
BTWQUESTS_RUMBLINGS_NEAR_FELTOTEM = "魔化圖騰附近的威脅"
BTWQUESTS_THE_BRADENSBROOK_INVESTIGATION = "布瑞登溪調查"
BTWQUESTS_THE_FOLLY_OF_LEVIA_LAURENCE = "蕾薇亞‧勞倫斯的愚行"
BTWQUESTS_THE_THIEVING_APPRENTICE = "偷竊的學徒"
BTWQUESTS_THE_TWISTED_TWINS = "扭曲的雙胞胎弟弟"
